export { default as About } from './About'
export { default as Client } from './Client'
export { default as FAQ } from './FAQ'
export { default as Partner } from './Partner'
export { default as Services } from './Services'
export { default as Home } from './Home'
